### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by riebling** [dustymabe/vagrant-sshfs#10]
Hey, first let me just say this plugin seems like a miracle solution to problems we've had configuring shared folders for a Vagrant VM running on AWS. (nfs proved impossible to get working cleanly, and rsync provided only 1-way synchronization) However, I'm not sure I understand correctly certain parts of the README, based on how they are presented, so maybe they could be enhanced.

 * zero, where it says "The idea is that if key1 is a key that is authorized to log in to the Vagrant host ,meaning there is an entry for key1 in the ~/.ssh/authorized_keys file, then you should be able to do the following to have a non-interactive experience with SSH keys and agent forwarding:" I know it's intuitive to someone familiar with ssh key generation and usage, but when referring to "the ~/.ssh/authorized_keys file" it's already gone over some of our heads. 
This file is not on my host. Is it in the guest? Did I have to do something to create this file in the guest? (Which I haven't yet because these things are supposed to happen before the guest exists, right? Before we do 'vagrant up') - these are the kind of dumb, panicky questions that go through the mind. Also, define "key1" - is this a public key, a private key, how was it created? Where is it - on the guest or host or in ~/.ssh.  It's that tricky part of clarifying whether something is a conceptual entity, like a variable name, or a concrete example, like a pathname (on a guest or host).

 * First, there are example command lines to set up and add your key to the agent, which begin with '#'.  Does this mean they need to be run as root, or is '#' just a shorthand for a generic default shell prompt?

 * Second, when talking about `key1`, what is it's relationship (if any) to private keys used to log into an AWS VM? I am accustomed to logging into a VM, once it has been started, with:

  `ssh -i /path/to/myAwsKey.pem ubuntu@ip.ip.ip.ip`

Can I use this same key as `/path/to/key1`? I guess not. It seems I need to use a public key. The key for AWS is a private key, and as it turns out, I have not generated a public key. Ah, the benefits of reading the linked background information on Key Generation and Key Forwarding :)

 * There is nothing wrong with how things are explained, but just to let you know, I wasn't sure whether `ssh_username` referred to the username on the host, or in the guest, and got it wrong the first time. Only after working backwards from the Vagrantfile configuration example (which is not a command line option? see below) did it come clear that it needs to be the host username ("The current user who is interacting with Vagrant")

 * Lastly, under Options, there are several "options that can be provided on the command line".  But the only example of how to use them is not in the form of a command line, but rather a stanza from a Vagrantfile. It would be nice to either see example command lines showing some of the options in use, or else maybe change the wording that introduces the options to mention that they can be used also in a Vagrantfile.

I'll read more the links on ssh Key Generation and Key Forwarding which may help me finally understand when the README is referring to things-on-the-host vs. things-in-the-guest. I know only enough to get myself into trouble, as is obvious by what's written here.

But thanks for this potentially life-saving plugin, can't wait to get it working!

**Comment by riebling** [comment]
So sorry for writing so much. But I think I understand now, and here was the basic problem. The documentation here assumes that you have a virtual machine that already exists, and by logging into that VM, you are able to get copy key data into authorized_keys on the local host.  Of course by configuring these things manually first, you can then achieve fully automated "vagrant up" without any need for baking in passwords or prompting for passwords.

But if I understand correctly, this is impossible to do for a Vagrant VM that does not yet exist, that is, when you are provisioning for the very first time. When you "vagrant up" this VM cannot possibly have any keys in it, or forward them somehow back to the host. (unless that is what forward_agent='true' does?) - I just can't see any scenario in which the authorized_keys file on the host gets automatically populated, either by typing things manually in the guest VM, or issuing commands on the host VM. 

Does this make sense? That somewhere it has been left out the business of how to make sure you have the right content in (or have at all) authorized_keys, and that the customary way to do this is to edit it by hand, putting the public keys of identities you wish to permit ssh access? In my example, if a Vagrant VM on AWS has the default username "ubuntu" then there needs to be a public key belonging to this "ubuntu" user placed in the authorized_keys of the host machine that launched the Vagrant VM on AWS.

**Comment by dustymabe** [comment]
hi @riebling - thanks for the message :)

Since there was so much feedback there I am going to try to address it but I may miss parts. First off I would like to say that I am planning to implement a mode that would no longer require ssh keys or username/password at all (see https://github.com/dustymabe/vagrant-sshfs/issues/11)  so I can clean up the documentation around those items and hopefully this will take care of you. Would you be happy with that? 

There was one other comment which I noticed as wrong:

> Lastly, under Options, there are several "options that can be provided on the command line".

Indeed you are correct! The statement is wrong. It should be "options that can be provided in the Vagrantfile". I have addressed this in https://github.com/dustymabe/vagrant-sshfs/pull/12/files. Thanks

If you want me to help you answer some of your other questions (confusion around SSH keys and such) then try to catch me in #fedora-cloud on Freenode IRC.

**Comment by riebling** [comment]
Thanks so much for responding.
I have actually gone ahead and used the DISCOURAGED prompt-for-password,
because it's exactly how we hope to allow a user to connect a remotely launched
AWS instance to their local filesystem via sshfs - by typing the password, which I
hope is more secure than storing it anywhere in a file (but of course less secure
than using ssh keys)

And it works!  So I have to apologize for venting my confusion over ssh key
generation, and which machine is the client to which server, since both directions
are present.  (For example a remotely launched AWS Instance will be a client to the
local sshfs shared folder.)

So the one you noticed as wrong is the only real worry about fixing, anything more
is just helping explain sshfs keys to newbies, and not a strict requirement, if you
want to keep the README clean and readable.

Much thanks, again,
-er

On 03/26/2016 01:52 PM, Dusty Mabe wrote:
>
> hi @riebling <https://github.com/riebling> - thanks for the message :)
>
> Since there was so much feedback there I am going to try to address it but I may miss parts. First off I would like to say that I am planning to implement a mode that would no longer require ssh keys or username/password at all (see #11 <https://github.com/dustymabe/vagrant-sshfs/issues/11>) so I can clean up the documentation around those items and hopefully this will take care of you. Would you be happy with that?
>
> There was one other comment which I noticed as wrong:
>
>     Lastly, under Options, there are several "options that can be provided on the command line".
>
> Indeed you are correct! The statement is wrong. It should be "options that can be provided in the Vagrantfile". I have addressed this in https://github.com/dustymabe/vagrant-sshfs/pull/12/files. Thanks
>
> If you want me to help you answer some of your other questions (confusion around SSH keys and such) then try to catch me in #fedora-cloud on Freenode IRC.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/dustymabe/vagrant-sshfs/issues/10#issuecomment-201905495>
>

-- 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by dustymabe** [comment]
Hi @riebling.. 

Do you mind trying out a custom build of vagrant-sshfs that I have done with some new code for #11. With this new stuff you shouldn't need to worry about passwords or ssh keys.

First uninstall the existing vagrant-sshfs plugin that you may have
installed:

```
$ vagrant plugin uninstall vagrant-sshfs
Uninstalling the 'vagrant-sshfs' plugin...
```

Then install a custom build that I have done:

```
$ vagrant plugin install vagrant-sshfs --plugin-source https://dustymabe.fedorapeople.org/gemrepo/
```

**Comment by riebling** [comment]
Sure, let me try it out. I've been refining things by developing on linux,
then deploying on OSX, and noticing some interesting differences.  ( We
want the same Vagrantfile to build systems that work with both VirtualBox
and AWS providers. )

I wanted to let you know a couple times I got errors that could not reproduce,
where the command Vagrant runs to install sshfs fails to find the sshfs debian
package.  Because it does not happen consistently, I consider it a "bizarro
timing problem" and won't worry about it.

On 03/29/2016 12:20 AM, Dusty Mabe wrote:
>
> Hi @riebling <https://github.com/riebling>..
>
> Do you mind trying out a custom build of vagrant-sshfs that I have done with some new code for #11 <https://github.com/dustymabe/vagrant-sshfs/issues/11>. With this new stuff you shouldn't need to worry about passwords or ssh keys.
>
> First uninstall the existing vagrant-sshfs plugin that you may have
> installed:
>
> |$ vagrant plugin uninstall vagrant-sshfs Uninstalling the 'vagrant-sshfs' plugin... |
>
> Then install a custom build that I have done:
>
> |$ vagrant plugin install vagrant-sshfs --plugin-source https://dustymabe.fedorapeople.org/gemrepo/ |
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/dustymabe/vagrant-sshfs/issues/10#issuecomment-202702187>
>

-- 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by dustymabe** [comment]
@riebling hopefully I have address most of your issues in 7676951 I'm going to close this now.

**Comment by dustymabe** [comment]
Closing #10 via 7676951
