### ISSUE TITLE
RHEL/CentOS 8 support

### ISSUE THREAD

**Issue by greg-hellings** [dustymabe/vagrant-sshfs#100]
RHEL/CentOS 8 is in beta now. There is currently no support for it in the plugin, so provisioning with SSHFS enabled fails when it attempts to install fuse-sshfs on the client system.

**Comment by dustymabe** [comment]
Thanks for reporting. will try to get around to fixing.

**Comment by greg-hellings** [comment]
Fixing will probably need to wait until there are public repos for EPEL 8, but just consider this a reminder/placeholder task. :+1:

**Comment by dustymabe** [comment]
👍

**Comment by dustymabe** [comment]
this is effectively blocked by: https://bugzilla.redhat.com/show_bug.cgi?id=1758884

**Comment by dustymabe** [comment]
> this is effectively blocked by: https://bugzilla.redhat.com/show_bug.cgi?id=1758884

ok, new update.. it all seems to work now with the `centos/8` box, but not because the above bug has been addressed. It seems the machines are able to install a very old version of fuse-sshfs from the repos:

```
[vagrant@c8 ~]$ rpm -q fuse-sshfs
fuse-sshfs-2.4-1.el6.x86_64
```

**Comment by dustymabe** [comment]
This only worked because `epel-release` from epel6 was getting installed (#100). A more appropriate fix is coming.
