### ISSUE TITLE
Install EPEL8 on RHEL-8 systems

### ISSUE THREAD

**Issue by pbrezina** [dustymabe/vagrant-sshfs#108]
EPEL6 is currently installed on RHEL-8 systems.

**Comment by dustymabe** [comment]
Yep that needs to be fixed. Though we also need to get sshfs into epel8. See https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/UZ7QRQIQ7UFDQRTKYEQNEK3RJCCOBAW7/#UZ7QRQIQ7UFDQRTKYEQNEK3RJCCOBAW7

**Comment by pbrezina** [comment]
Thank you for quick fix, however it is not correct. `epel-release` is actually not available in RHEL unless you have EPEL already enabled. See https://repology.org/project/epel-release/versions

**Comment by dustymabe** [comment]
I actually modified it to not use epel at all for el8: https://github.com/dustymabe/vagrant-sshfs/commit/ac732ace27c6991f89b808edb50f004bbaa87c70

but I think maybe that answer only works for CentOS and not RHEL. Any idea the magic yum command to run to install fuse-sshfs on RHEL?

**Comment by pbrezina** [comment]
fuse-sshfs is available in CRB (Code Ready Builder) repository in RHEL-8 so the name is different then what's in CentOS. But I guess you need some sort of subscription to enable this repository so it's not very suitable for vagrant and maybe it would be better to install it from some copr repository?

Because `epel-release` is only available in EPEL repository it will fail to install it even on RHEL-7/6.

**Comment by dustymabe** [comment]
Hey @pbrezina. It really looks like there aren't a lot of good options here. Now that there is proper detection for CentOS itself in Vagrant I reset the RHEL module back to what it was before (see f4408e3) and I decided to just do a best effort for RHEL8 by just installing the fuse-sshfs from epel7 (see 04235d9). CentOS still pulls from PowerTools repo like it should.

Do you want to try out the new release and make sure it works as you would expect it to on RHEL (6/7/8)?

**Comment by pbrezina** [comment]
Using EPEL6 broke dependencies when running system upgrade so it will probably be also issue with EPEL7. I think the best solution would be to try to install fuse-sshfs but say that "fuse-sshfs must be installed from code ready builder repo manually" if the package is not found.

**Comment by dustymabe** [comment]
> Using EPEL6 broke dependencies when running system upgrade so it will probably be also issue with EPEL7. 

Yeah. I'm trying to address that problem in https://github.com/dustymabe/vagrant-sshfs/commit/04235d96fb9d3d373a0c83b2e3f47a709f4c38af by not leaving epel7 installed on the system. Did you check out the commit? 

I think the best solution would be to try to install fuse-sshfs but say that "fuse-sshfs must be installed from code ready builder repo manually" if the package is not found.

**Comment by pbrezina** [comment]
I didn't notice this change. I will try it later this week to see if there is any impact.

**Comment by pbrezina** [comment]
Seems to work fine on both rhel7 and rhel8. I didn't notice any problem with package updates so it should work as long as fuse and fuse-common will be compatible.

**Comment by pbrezina** [comment]
Thank you for your work.
