### ISSUE TITLE
SSHFS not installed in centos/7 guests

### ISSUE THREAD

**Issue by jcarnu** [dustymabe/vagrant-sshfs#112]
With 
  * vagrant 2.2.9
  * vagrant-sshfs (1.3.4, global)

It turns out fuse-sshfs rpm is never installed (pulled from epel) on guest.
After some investigations I figured out `sshfs_install`  and ` sshfs_installed`  capabilities led to `cap/guest/redhat/sshfs_client.rb` but that no install were done due to `rhel_version` having `:centos_7` value.

There's two way to fix the situation (I implemented and tested both) : 

  * Creating a `centos` capability along with it's own `sshfs_client.rb` file including only `:centos_7` key
  * Adding a `:centos_7`  in ` cap/guest/redhat/sshfs_client.rb`  here https://github.com/dustymabe/vagrant-sshfs/blob/9fcb721bf7b406d27273f44cba7924c22de9e7fd/lib/vagrant-sshfs/cap/guest/redhat/sshfs_client.rb#L20

As I'm not very acquainted with that plugin code, I'm not able to identify other places where those changes should be also done and if my changes lead to regressions...

This behaviour does not appear on vagrant 2.0.2 where centos/7 boxes appear as `redhat` guest `rhel_version`.

I can provide with both PR but as the second one is quite straightforward I'd better like to be sure to come with the right solution (and be sure that there's no regressions anywhere else)

**Comment by dustymabe** [comment]
hey @jcarnu this should be fixed in the latest release thanks to #111 - try it out and let us know how it works.
