### ISSUE TITLE
No epel-release-latest-6.noarch.rpm for rhel6

### ISSUE THREAD

**Issue by jormangand** [dustymabe/vagrant-sshfs#122]
When using Amazon Linux 2 as guest OS (https://app.vagrantup.com/bento/boxes/amazonlinux-2), the attempt to access EPEL fails:

```
==> default: Installing SSHFS client...
       The following SSH command responded with a non-zero exit status.
       Vagrant assumes that this means the command failed!

       rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

       Stdout from the command:

       Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

       Stderr from the command:

       curl: (22) The requested URL returned error: 403 Forbidden
       error: skipping https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm 
       - transfer failed
```

epel_install() in cap/guest/redhat/sshfs_client.rb uses a hard-coded path in EPEL:

`rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm`

which is no longer present (only versions 7 and 8 remain).

The flavor seems to resolve to rhel (rhel6), although running cat /proc/version on the guest indicates RHEL7:
`Linux version 4.14.198-152.320.amzn2.x86_64 (mockbuild@ip-10-0-1-118) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-9) (GCC)) #1 SMP Wed Sep 23 23:57:28 UTC 2020`

It would be nice to parameterise this somehow.

**Comment by h0st** [comment]
I've also faced with the same issue using CentOS 8 official box (centos/8) and vagrant-sshfs plugin. epel-release-latest-6.noarch.rpm package is missing by https://dl.fedoraproject.org/pub/epel/ url. I am trying to change it to epel-release-latest-8.noarch.rpm. 

I am agree with @jormangand or it could be replaced to the latest rpm version.

```
==> pb01: Installing SSHFS client...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

Stdout from the command:
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

Stderr from the command:
curl: (22) The requested URL returned error: 403 Forbidden
error: skipping https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm - transfer failed
```

**Comment by giorgioma** [comment]
I am temporarily fixing it by provisioning the install directly on the vagrant shell for CentOS
```
config.vm.provision "shell", inline: <<-SCRIPT
      yum -y install --enablerepo=PowerTools fuse-sshfs
SCRIPT
```

**Comment by h0st** [comment]
Updating the plugin to a version upper than 1.3.4 helped me on CentOS.

**Comment by h0st** [comment]
New troubles on a CentOS 8.3.2011:

CentOS Linux release 8.3.2011 and vagrant-sshfs 1.3.5:
```
==> h01: Installing SSHFS client...
==> h01: Removing domain...
==> h01: Running cleanup tasks for 'reload' provisioner...
==> h01: Running cleanup tasks for 'reload' provisioner...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum -y install --enablerepo=PowerTools fuse-sshfs

Stdout from the command:

Stderr from the command:

Error: Unknown repo: 'PowerTools'
```

CentOS Linux release 8.3.2011 and vagrant-sshfs 1.3.4:
```
==> pb01: Installing SSHFS client...
==> pb01: Mounting SSHFS shared folder...
==> pb01: Mounting folder via SSHFS: /root/vagrant-libvirt/deployment-environments/kvm => /vagrant
==> pb01: Checking Mount..
==> pb01: Checking Mount..
==> pb01: Checking Mount..
==> pb01: Checking Mount..
==> pb01: Checking Mount..
==> pb01: Checking Mount..
==> pb01: Checking Mount..
==> pb01: Removing domain...
==> pb01: Running cleanup tasks for 'reload' provisioner...
==> pb01: Running cleanup tasks for 'reload' provisioner...
Mounting SSHFS shared folder via slave SSHFS mount failed. Please
look at the below STDERR output from the processes that were run.

SSH command:

Warning: Permanently added '192.168.121.21' (ECDSA) to the list of known hosts.
sudo: sshfs: command not found

SFTP command:
```

Log file attached.
[sshfs-1.3.4.log](https://github.com/dustymabe/vagrant-sshfs/files/5678936/sshfs-1.3.4.log)

**Comment by giorgioma** [comment]
`yum -y install --enablerepo=powertools fuse-sshfs`
does work

There might be something wrong with my plugin install, but I am still seeing this error on 1.3.5

**Comment by h0st** [comment]
My current working setup:
- CentOS Linux release 8.3.2011
- Vagrant 2.2.10
- centos/8 (libvirt, 2011.0) – latest
- vagrant-sshfs (1.3.5)

And yes, as mentioned @giorgioma - replace PowerTools to powertools in a vagrant-sshfs plugin sshfs_client.rb file like this: 
```
sed -i 's/PowerTools/powertools/g' /home/<your_user>/.vagrant.d/gems/2.6.6/gems/vagrant-sshfs-1.3.5/lib/vagrant-sshfs/cap/guest/centos/sshfs_client.rb. 
```
It was observed only on the latest centos/8 box.

**Comment by dustymabe** [comment]
I think all of this should be taken care of in the latest release (`v1.3.6`).
