### ISSUE TITLE
owner and group not working

### ISSUE THREAD

**Issue by rednaks** [dustymabe/vagrant-sshfs#127]
it seems that sshfs is not mounting the folders with the given `owner` and `group`. is it supported by the plugin ? if not maybe it's worth logging a warning or an error to say that they're not supported.

Thanks.

**Comment by tuupola** [comment]
I noticed the same but only with VirtualBox provider. When using libvirt provider both `owner` and `group` settings seem to work.

**Comment by tuupola** [comment]
Also currently with libvirt provider files get mounted as `vagrant:vagrant` but with VirtualBox provider files get mounted as `53:games`. This is with `centos/7` box. The `vagrant:vagrant` works for me, but currently with VirtualBox this is impossible because `owner` and `group` settings are not honored.

**Comment by rednaks** [comment]
@tuupola  I submitted a patch but the project seems dead : https://github.com/dustymabe/vagrant-sshfs/pull/128

**Comment by tuupola** [comment]
There has been some activity this year so lets wait for a while. It is pity many Vagrant related projects get forgotten because it is not as sexy as Docker.

**Comment by dustymabe** [comment]
Hey @rednaks @tuupola - regarding setting the `-o uid` and `-o gid` option for the SSHFS mount you should be able to do this via the generic [`sshfs_opts_append`](https://github.com/dustymabe/vagrant-sshfs#generic-options) option.

I'm trying to understand the problem a bit more here though. @rednaks, you mention

> not mounting the folders with the given `owner` and `group`

Where are you providing `owner` and `group`? Can you give more details?

@tuupola, I'd like to understand the issue with VirtualBox more. Unfortunately I don't currently have a VBox setup. What Host OS are you on? What does your Vagrantfile look like? What does the mount look like in the guest (`ls -l` on the mountpoint).

**Comment by dustymabe** [comment]
Thanks @rednaks - I was unaware of that. I'll dig in further.

Thank you for the pointer.

**Comment by tuupola** [comment]
I had missed all this discussion. In any case thanks for the new release!
