### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by tuupola** [dustymabe/vagrant-sshfs#132]
This project is really useful but has not had any activity for 12 months. Is it still being maintained? If not, maybe additional maintainers needed? Or maybe Red Hat / Fedora could sponsor the maintenance? It is after all included in the distribution.

**Comment by dustymabe** [comment]
hey @tuupola - The answer is complicated. I still care about the project, just have had a lot going on recently. Will try to get back to it and address open issues soon.

**Comment by tuupola** [comment]
No problem, I know how it goes. Been there myself too more than once. I am personally mostly interested in https://github.com/dustymabe/vagrant-sshfs/pull/130 because Fedora 36 bundled Vagrant now also supports Rocky Linux. In any case thanks for [vagrant-sshfs](https://github.com/dustymabe/vagrant-sshfs) it has been a life saver!
