### ISSUE TITLE
new files appear in box with about 15 s delay

### ISSUE THREAD

**Issue by optak** [dustymabe/vagrant-sshfs#18]
If I create file on host, I can see it in box after about 15 second (ls file), but if I want to read that file, I can immediately (cat file).
For other direction, I can see no delay.

**Comment by dustymabe** [comment]
Hey @optak - so this looks like the behavior of sshfs itself. There are a lot of options that sshfs has (man sshfs) that can be used to change the level of caching etc that is done. By default I am using `noauto cache` because we'd really like things to be correct. This may be why you see the delay.

**Comment by optak** [comment]
I'm not telling it's a big problem, if you can find option to lower time between sync  it would be great, otherwise I think that a note in documentation is enough.

**Comment by dkutalek** [comment]
I can see similar behaviour on Mac.

On guest, I run:
tail -f /Users/dkutalek/blah.txt

On host I do:
date >> /Users/dkutalek/blah.txt

It takes about 20 seconds to see tail write out date line from host.
Other way it is immediate (1 second or less).

When looking into man page, it seems noauto_cache is FUSE option
and there is also SSHFS option cache_timeout defaulting to 20s,
which is about what I see. That mught be the source of issue?

**Comment by dustymabe** [comment]
@dkutalek yeah I think these are all settings of sshfs. @optak you can change these settings if you'd like by using `sshfs_opts_append` as described in https://github.com/dustymabe/vagrant-sshfs#generic-options 

should we close this issue?

**Comment by optak** [comment]
@dustymabe I think taht it may confuse many users. I would like to do one of these things before closing:
1) mention this behaviour in doc (explicitely that there is 20s default timeout, which mean that files will appear with delay)
2) lower timeout by default to such short time that users can hardly spot the delay, I would say <= 3s
3) disable caching in sshfs

Option 2 and 3 can have impact to performance.

**Comment by dustymabe** [comment]
hey @optak, for now I am going to document this in the FAQ. If we want to set this option in the ADB then we do it at that level if that is ok.
