### ISSUE TITLE
sshfs slave mode doesn't work with cmd.exe/powershell

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/vagrant-sshfs#24]
NOTE: I had to hack around with the paths on vagrant-sshfs-1.1.0 to get this to work to begin with

The `sftp-server` process that gets kicked off on the host when running vagrant-sshfs seems to immediately get axed once the `vagrant up` or `vagrant sshfs` command exit.  This is a snippet of what it looks like:

```
==> default: Folder Successfully Mounted!
remote host has disconnected
```

We either need to more clearly require cygwin, or find a way to work around this.

On a side note using the old mode where we connect to an SSH daemon that is running on the windows host does work.

**Comment by Moymee** [comment]
Can I have more insight on the the vagrant issue with the powershell in windows..?

**Comment by dustymabe** [comment]
hi @Moymee - for some reason in powershell/cmd.exe when we spawn off processes [here](https://github.com/dustymabe/vagrant-sshfs/blob/master/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb#L160) the side effect is that as soon as the processes are spawned off they then get killed once the ruby vagrant process (i.e. the `vagrant up` or `vagrant sshfs` command) ends. 

In other words it looks like daemonizing the processes when running under powershell or cmd.exe doesn't work. The processes get started just fine but then get cleaned up. Under cygwin it looks like it works fine. I don't know why this is.

**Comment by whren** [comment]
I'm quite in your context @dustymabe but I faced other issue than yours (#25) and finally get it working.

**Comment by dustymabe** [comment]
I think this is solved now that we are using win32-process. Added in #33 - 3b81711
