### ISSUE TITLE
Minor release for vagrant-sshfs

### ISSUE THREAD

**Issue by praveenkumar** [dustymabe/vagrant-sshfs#30]
Can we do a minor release `1.1.1` for vagrant-sshfs, It has been a long time we had any release and some patches are already merged which have improvement from `1.1.0` release so I think it's better to do a minor release and include all those improvements.

**Comment by dustymabe** [comment]
Just released 1.2.0 yesterday https://github.com/dustymabe/vagrant-sshfs/releases/tag/v1.2.0
