### ISSUE TITLE
lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:in `spawn': No such file or directory

### ISSUE THREAD

**Issue by naina-verma** [dustymabe/vagrant-sshfs#32]
@dustymabe  , I am trying to do vagrant up on my windows 10 Pro machine and using cmd.exe for this, It throws lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:142:in `spawn': No such file or directory 
Link to complete logs (https://gist.github.com/naina-verma/73297d18e8d1fa7cb5b1984d16ceb948)

I have tried this same Vagrantfile with cygwin setup it works like a charm but its not working with powershell and cmd prompt.

When i commented  `if Vagrant::Util::Platform.windows?` till `SHELL` then it works fine

**Comment by dustymabe** [comment]
hey @naina-verma - can you test this out with the latest pre-release to see if you are still having issues?

here is how to test:
```
vagrant plugin uninstall vagrant-sshfs
wget https://dustymabe.fedorapeople.org/gem/vagrant-sshfs-1.1.0.dev.gem
vagrant plugin install ./vagrant-sshfs-1.1.0.dev.gem
```

**Comment by naina-verma** [comment]
Sure @dustymabe , i will give it a try

**Comment by naina-verma** [comment]
@dustymabe ,
I have tested those changes it works fine on cygwin,cmd but with powershell there is an issue with 1.7.4,1.8.4 and 1.8.5 vagrant versions.
Its not working with any of one vagrant version on powershell.Otherwise it works fine


`C:\Users\cdk\XYZ\cdk\cdk\components\rhel\misc\hyperv\rhel-ose-hyperv>vagrant status
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

126: The specified module could not be found.   - C:/Users/cdk/.vagrant.d/gems/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so`

**Comment by naina-verma** [comment]
@dustymabe ,
I tested it with landrush (1.1.0.beta.3), and it works fine.
The above problem was due to older version of landrush installed on test machine

**Comment by dustymabe** [comment]
@naina-verma thanks - I'm going to close this as fixed.
