### ISSUE TITLE
Detection of sftp-server is not always working

### ISSUE THREAD

**Issue by hferentschik** [dustymabe/vagrant-sshfs#35]
_synced_folder.rb_ does something like this to add the _sftp-server.exe_ executable to the PATH:

    cygwin_root = Vagrant::Util::Platform.cygwin_windows_path('/')
    ENV['PATH'] += ';' + cygwin_root + '\usr\sbin'

This does not always seem to work. I am getting:

    The 'sftp-server' executable file can't be found on the host machine but
    is required for sshfs mounting to work. Please install the software and
    try again.

where sftp-server is in _/user/sbin/_ of a cygwin install which is rooted at _C:\cygwin64_.

**Comment by dustymabe** [comment]
See https://github.com/dustymabe/vagrant-sshfs/pull/34 - does that solve this problem? That being said we can't be mind readers so we ultimately don't know where someone installed cygwin unless they are running under a cygwin terminal.

**Comment by dustymabe** [comment]
rebase your PR on latest upstream master to pull in this change

**Comment by dustymabe** [comment]
I'm going to close this since #34 and bd62fd2 is in. Please re-open if that doesn't solve the problem
