### ISSUE TITLE
mount checking doesn't handle symlinks

### ISSUE THREAD

**Issue by cgwalters** [dustymabe/vagrant-sshfs#44]
On Atomic Host (ostree), `/home -> /var/home`.  This causes the scraping of `/proc/mounts` (which has the path canonicalized via `/sbin/mount`) to fail to match.

Ultimately, what we really want to do is monitor the health of the `sshfs` process, and also get a "ready" notification from it.  I think it might work to use a systemd unit `Type=forking`, since FUSE servers normally daemonize after success.  See also https://bugzilla.redhat.com/show_bug.cgi?id=916780

**Comment by dustymabe** [comment]
hey @cgwalters - i'll take a look at list and get back to you. Sorry about the delay.
