### ISSUE TITLE
working with scoop openssh

### ISSUE THREAD

**Issue by todiadiyatmo** [dustymabe/vagrant-sshfs#45]
Hi !
I tried use the sshfs using cygwin and workgreat, i tried use scoop but it wont mount, any idea ?

Regards,
Todi !

**Comment by todiadiyatmo** [comment]
https://github.com/lukesampson/scoop

^^ this one i mean, it is a package manager installer

**Comment by dustymabe** [comment]
hi @todiadiyatmo - what exactly did you install using scoop? openssh or sshfs? Can you share your sshfs lines from your Vagrantfile?

**Comment by dustymabe** [comment]
ping @todiadiyatmo

**Comment by dustymabe** [comment]
ping @todiadiyatmo

**Comment by dustymabe** [comment]
closing this as I haven't heard back and the problem is not very well defined.
