### ISSUE TITLE
New minor release for plugin

### ISSUE THREAD

**Issue by praveenkumar** [dustymabe/vagrant-sshfs#53]
Looks like from master to last release there are some documents migration and few bugs fixes happen. @dustymabe Can you do a minor release for the plugin?

**Comment by dustymabe** [comment]
I'll try to get one out tomorrow and comment back here. If I don't get to it, the previous version should suffice as it's only a few commits difference (mostly docs).

**Comment by praveenkumar** [comment]
@dustymabe we actually care for https://github.com/dustymabe/vagrant-sshfs/pull/50 which was after previous release.

**Comment by dustymabe** [comment]
New release is out - see https://github.com/dustymabe/vagrant-sshfs/releases/tag/v1.2.1
