### ISSUE TITLE
sshfs install fails on AWS EC2 Ubuntu 16.04 server cloud image

### ISSUE THREAD

**Issue by riebling** [dustymabe/vagrant-sshfs#58]
Hey, this works fine for Ubuntu 14.04, but when I just tried bringing up a VM
that uses sshfs on a 16.04 AMI, I get this error and 'vagrant up' stops:
```
==> default: Installing SSHFS client...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get install -y sshfs

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...


Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
E: Unable to locate package sshfs
```
This might not be your fault though! There is another mysterious error I see as well... a check for python returns false, even though python IS THERE.  I'll come back here with what I discover, but for now just wanted to note this in case anyone else has observed the same thing.

**Comment by dustymabe** [comment]
@riebling, thanks for the report. I look forward to seeing what you find.

**Comment by dustymabe** [comment]
@riebling what did you find?

**Comment by riebling** [comment]
The problem was specific to the particular 16.04 Ubuntu cloud image being requested, which did not support installing sshfs. I don't have the failing version with me at the moment, but an AMI that is known to work can be found by specifying parameters like the below to the [Ubuntu Cloud Image Finder](https://cloud-images.ubuntu.com/locator/)  

```
Cloud 	Zone 	Name 	 	Version 	Arch 	Instance Type 	Release 	ID
Amazon AWS	us-east-1	xenial	16.04	amd64	hvm-instance	20161115	ami-abbc94bc 
```
