### ISSUE TITLE
Apache access to mounted file

### ISSUE THREAD

**Issue by Ziemowit** [dustymabe/vagrant-sshfs#6]
Is it possible to load web site by Apache after mount by your tool?

Because when I have been trying to use previous version (0.8) before you take the control over plugin development I have been receiving:

```Forbidden

You don't have permission to access / on this server.
Apache/2.4.12 (Ubuntu) Server at xxx.yyy.com Port 443
```

Maybe in your it works?

**Comment by dustymabe** [comment]
hi @Ziemowit. I just tried and was able to get this to work. I set the shared folder location within the guest as the Document root for apache and disabled selinux (I used Fedora and not Ubuntu). 

Also make sure you have configured apache to allow access to the system: http://httpd.apache.org/docs/2.4/upgrading.html#access

If you can't get things to work right for you I can try to send you a Vagrantfile that you can try on your end to see if it works for you.

**Comment by Ziemowit** [comment]
Hmmm I am a little bit lost. When I have upgrade to version 1.0 I have following problem:

```
Mounting SSHFS shared folders failed. This is most often caused by either
an SSH Daemon not running on the host or invalid credentials being provided.
Please make sure an SSH daemon is running on the host and proper credentials 
were provided to be able to authenticate via SSH.
```
My config is:

```
config.vm.synced_folder "/home/esg/VM/interscape/interscape-frontend", 
                                       "/home/esg/VM/interscape/interscape-frontend", 
                                       type: "sshfs",
                                       ssh_username: "esg"
```

Even if I put correct password then I receive this message...

**ps aux | grep sshd** claims that for my user sshd is running.

**Comment by dustymabe** [comment]
Hey @Ziemowit,

From your output it looks like the sshfs client didn't get installed in the guest properly.

```
bash: line 2: sshfs: command not found
```

You are using ubuntu, correct? It should get installed automatically in the guest, but there might be a bug. Can you make sure the sshfs package is installed in the guest? You should be able to verify with: `dpkg -l sshfs`

**Comment by Ziemowit** [comment]
Heh I have checked it. 
So when I am using it with CoreOs box it does not work.
But when I have downloaded ubuntu/trusty to vagrant the everything works.

So it may be some problem with CoreOs distribution for vagrant. I will try to reinstall.

But I have found one more thing. In previous solution (v0.8) when you had halted vagrant then mounted directory disappeared. But in current solution it does not. As I understand right now you just copy files from guest to host machine. And they will be still visible even if you halt the guest (virtual machine).

**Comment by dustymabe** [comment]
> So it may be some problem with CoreOs distribution for vagrant. I will try to reinstall.

With this solution the folder is mounted "from the host, into the guest", which means the files live on the host, but are simply network mounted into the guest. This means the guest needs to have the sshfs client software installed inside. CoreOS doesn't have sshfs installed inside of it so I may try to investigate if there is a way to get it to work running from a container.

> But I have found one more thing. In previous solution (v0.8) when you had halted vagrant then mounted directory disappeared. But in current solution it does not. As I understand right now you just copy files from guest to host machine. And they will be still visible even if you halt the guest (virtual machine)?

So since we are mounting "from the host, into the guest" the files **live** on the host. Thus the files will not go away. This is how synced folder implementations behave traditionally.

**Comment by Ziemowit** [comment]
Thanks. Everything is clear now :)
