### ISSUE TITLE
support skipping guest provisioning

### ISSUE THREAD

**Issue by cgwalters** [dustymabe/vagrant-sshfs#63]
This project doesn't currently know about rpm-ostree, and the problem is that it runs before any project-specific provisioning occurs, which makes it hard to do.

Further, some users may not want to unconditionally enable EPEL for example.  So maybe something like:

```
    admin1.vm.synced_folder ".", "/var/home/vagrant/sync", type: 'sshfs', provision: false
```

**Comment by dustymabe** [comment]
what would you suggest `provision: false` to do?

**Comment by cgwalters** [comment]
Don't do any of the things to install packages; though what we may really need is a way to run provisioners both before and after sshfs.  That said, maybe we should just assume more boxes bake in sshfs.

**Comment by dustymabe** [comment]
When the plugin runs it detects if sshfs is already installed (doesn't matter how it was installed) and doesn't try to install it again.

Let me know why this doesn't work. The only other thing I can think of that you would want is to just disable the attempt to do the mount with 'disabled: true'

**Comment by cgwalters** [comment]
Don't worry about this, in the end we need to include this by default in Vagrant boxes.
