### ISSUE TITLE
Windows does not support the capability 'sshfs_forward_is_folder_mounted'

### ISSUE THREAD

**Issue by mohamaa** [dustymabe/vagrant-sshfs#64]
I tried using this plugin but got following error:

`
Vagrant attempted to execute the capability 'sshfs_forward_is_folder_mounted' on the detect guest OS 'windows', but the guest doesn't support that capability. This capability is required for your configuration of Vagrant. Please either reconfigure Vagrant to avoid this capability or fix the issue by creating the capability.`

**Comment by dustymabe** [comment]
Looks like your vagrant guest is a windows box? 

Windows does not have an ssh daemon installed by default unless you have modified the box to have it. This plugin has been targeted at sharing folders with linux guests.

**Comment by dustymabe** [comment]
Closing this. Unfortunately we don't support Windows guests at this time.

**Comment by matstatman** [comment]
Windows 2019 and 2022 now has a build in openssh server, same error
