### ISSUE TITLE
Support vagrant-lxc

### ISSUE THREAD

**Issue by varac** [dustymabe/vagrant-sshfs#68]
Hej, 

first of all th for this awesome plugin, I was so lucky to finally remove NFS from my box !
It works great with vagrant-libvirt, but fails with vagrant-lxc:

```
--- vagrant/fgrehm » vagrant up --provider=lxc     

Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
Bringing machine 'default' up with 'lxc' provider...
==> default: Importing base box 'fgrehm/precise64-lxc'...
==> default: Checking if box 'fgrehm/precise64-lxc' is up to date...
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.0.3.196:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Installing SSHFS client...
==> default: Mounting SSHFS shared folder...
==> default: Mounting folder via SSHFS: /home/varac/vagrant/fgrehm => /vagrant
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
Mounting SSHFS shared folder via slave SSHFS mount failed. Please
look at the below STDERR output from the processes that were run.

SSH command:

Warning: Permanently added '10.0.3.196' (ECDSA) to the list of known hosts.
fuse: device not found, try 'modprobe fuse' first

SFTP command:

```

A proper fix would be appreciated!

**Comment by dustymabe** [comment]
hmm. so sshfs uses fuse (kernel module) and you are running a container which means you are sharing the kernel with the host. You might be able to `modprobe fuse` on the host before doing `vagrant up` and see if that works.

**Comment by varac** [comment]
@dustymabe my kernel has fuse included, not as a module:

```
--- ~ » lsmod |grep fuse
--- ~ » modprobe fuse
--- ~ » lsmod |grep fuse
```

even trying `modprobe fuse` explictily on my host it fails the same.

**Comment by dustymabe** [comment]
does `/dev/fuse` exist on your host?

**Comment by dustymabe** [comment]
@varac ^^

**Comment by varac** [comment]
@dustymabe yes it does

```
--- ~ » ls /dev/fuse -la
crw-rw-rw- 1 root root 10, 229 Feb 11 14:09 /dev/fuse

```

**Comment by dustymabe** [comment]
can you try to bind mount that into the container? I have no idea how to do this with vagrant-lxc, but I believe that is what needs to be done.

**Comment by varac** [comment]
@dustymabe Thx for looking into this. But I didn't debug further, I'm fine with vagrant-lxc with it's default way of mounting shared folders.

**Comment by robkinyon-roivant** [comment]
What's needed here is a verification that `/dev/fuse` exists **on the guest** and, if not, execute `mknod -m 666 /dev/fuse c 10 229`. This is a well-known issue in mounting sshfs within LXC containers.

Failed attempts:

* Because of https://github.com/hashicorp/vagrant/issues/936, you cannot do this from within the Vagrantfile as a provisioning step.
* I tried to set things up so that the synced folder was disabled, then I would provision everything, then run `vagrant sshfs --mount` with a `:host_script` provisioning step, but that didn't work because the synced folder is **disabled**. :(

Finally, this also has to be done on every run because, if the device doesn't exist in the container template, it won't exist on reboot either.
