### ISSUE TITLE
vagrant up vs vagrant sshfs path differences

### ISSUE THREAD

**Issue by jdoss** [dustymabe/vagrant-sshfs#72]
Using ~ in the host path will cause issues when using vagrant sshfs. Use the example Vagrant file.

```
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"
  config.vm.synced_folder "~/", "/sharedhome", type: "sshfs"
end
```
If you `vagrant up` it will  expand the path: 

```Mounting folder via SSHFS: /home/dustymabe => /sharedhome```

but `vagrant sshfs` will not:

```Mounting folder via SSHFS: ~/ => /sharedhome```

and it will result in a failure. 

```==> default: Mounting folder via SSHFS: ~/ => /opt/app/sharedhome
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
Mounting SSHFS shared folder via slave SSHFS mount failed. Please
look at the below STDERR output from the processes that were run.

SSH command:

Warning: Permanently added '192.168.121.73' (ECDSA) to the list of known hosts.
:~/: No such file or directory


SFTP command:
```

**Comment by dustymabe** [comment]
hey @vincenzo I think this is the same problem as what you reported here: https://github.com/dustymabe/vagrant-sshfs/issues/61#issuecomment-264688564. Do you agree?

**Comment by vincenzo** [comment]
@dustymabe It might be, if you are implying that they are both down to a failed expansion of `~`.

**Comment by dustymabe** [comment]
yes, I believe that is the case.
