### ISSUE TITLE
sftp-server executable file can't be found

### ISSUE THREAD

**Issue by spicysomtam** [dustymabe/vagrant-sshfs#83]
Target os is redhat 7.4. Doing a find for this on the OS, I find it here, and its part of this rpm:

```
# find / -name sftp-server
/usr/libexec/openssh/sftp-server
# rpm -qf /usr/libexec/openssh/sftp-server
openssh-server-7.4p1-11.el7.x86_64
```
Maybe you need to add this to the path you search? Plugin is v1.3.0 and its vagrant 2.x.

**Comment by dustymabe** [comment]
We already check `/usr/libexec/openssh/` [here](https://github.com/dustymabe/vagrant-sshfs/blob/master/lib/vagrant-sshfs/synced_folder.rb#L113).

The most important detail here is that this is the `sftp-server` from the host, not the target guest OS.

**Comment by spicysomtam** [comment]
Ah. Yes I am missing openssh-sftp-server on my host (I am using Ubuntu). Thanks for the help.

**Comment by dustymabe** [comment]
No Problem
