### ISSUE TITLE
reverse sshfs on windows

### ISSUE THREAD

**Issue by sirber** [dustymabe/vagrant-sshfs#85]
I'm trying to get the pluygin to work on Windows 10. I installed VirtualBox 5, Vagrant 2, and the plugin.

Config: config.vm.synced_folder 'C:\Data\mnt', "/vagrant", type: 'sshfs', reverse: true

# vagrant up
no mount

# vagrant sshfs -- mount
The capability 'sshfs_reverse_is_folder_mounted' could not be found. This is an internal error
that users should never see. Please report a bug.

**Comment by dustymabe** [comment]
for technical reasons reverse mounting isn't supported on windows. See https://github.com/dustymabe/vagrant-sshfs/issues/74
