### ISSUE TITLE
How to properly setup folder mounting in Windows?

### ISSUE THREAD

**Issue by reypm** [dustymabe/vagrant-sshfs#97]
I am trying to setup Vagrant and Hyper-V and it is almost done but folder sharing is failing. This is how my `Vagrantfile` looks like:

    # -*- mode: ruby -*-
    # vi: set ft=ruby :
    
    Vagrant.configure("2") do |config|
      config.vm.box = "centos/7"
      config.vm.network :forwarded_port, host: 8080, guest: 80
      config.vm.network "private_network", ip: "192.168.50.4"
      config.vm.synced_folder "../../applications", "/var/www", type: "sshfs", , sshfs_opts_append: "-o cache=no"
    
      config.vm.provider :hyperv do |vb|
        vb.memory = "2048"
        vb.vmname = "centos7"
      end
    end

When I ran the command `vagrant up` I got the following:

    λ vagrant up
    Bringing machine 'default' up with 'hyperv' provider...
    ==> default: Verifying Hyper-V is enabled...
    ==> default: Verifying Hyper-V is accessible...
        default: Configuring the VM...
    ==> default: Starting the machine...
    ==> default: Waiting for the machine to report its IP address...
        default: Timeout: 120 seconds
        default: IP: 192.168.0.103
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 192.168.0.103:22
        default: SSH username: vagrant
        default: SSH auth method: private key
    ==> default: Machine booted and ready!
    ==> default: Mounting SSHFS shared folder...
    ==> default: Mounting folder via SSHFS: E:/Development/applications => /var/www/html
    ==> default: Checking Mount..
    ==> default: Checking Mount..
    ==> default: Checking Mount..
    ==> default: Checking Mount..
    ==> default: Checking Mount..
    ==> default: Checking Mount..
    ==> default: Checking Mount..
    Mounting SSHFS shared folder via slave SSHFS mount failed. Please
    look at the below STDERR output from the processes that were run.
    
    SSH command:
    
    Warning: Permanently added '192.168.0.103' (ECDSA) to the list of known hosts.
    fuse: mountpoint is not empty
    fuse: if you are sure this is safe, use the 'nonempty' mount option
    
    
    SFTP command:

Can any help me to setup this properly? Why I am missing here?

**Comment by dustymabe** [comment]
```
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
```

`/var/www` inside the vagrant VM already has files under it (i.e. it's not an empty directory) so fuse is complaining. You can either delete the files under `/var/www/` or add the `nonempty` mount option using [sshfs_opts_append](https://github.com/dustymabe/vagrant-sshfs#generic-options)
