### ISSUE TITLE
fuse: unknown option `slave'

### ISSUE THREAD

**Issue by mika018** [dustymabe/vagrant-sshfs#98]
I am trying to mount the vm folder to a host directory using:
`
vm1a.vm.synced_folder "/path/on/my/machine", "/path/on/vm",  type: "sshfs"
`
But I got an error saying that I have to use `nonempty` flag which I added and now my Vagrantfile looks like this:
`
vm1a.vm.synced_folder "/path/on/my/machine", "/path/on/vm", sshfs_opts_append: "-o nonempty", type: "sshfs"
`
When trying to get the sshfs running using `vagrant sshfs --mount` and after printing `Checking Mount...` for like 7 times this error is printed:
```
Mounting SSHFS shared folder via slave SSHFS mount failed. Please
look at the below STDERR output from the processes that were run.

SSH command:

Warning: Permanently added '[127.0.0.1]:2201' (ECDSA) to the list of known hosts.
fuse: unknown option `slave'

SFTP command:
```
I couldn't find any issue reporting this nor useful resources online. Any ideas?

**Comment by dustymabe** [comment]
What is the target vagrant box operating system? I'm guessing the version of sshfs you have doesn't support the `-o slave` option. Maybe check the man page to see.

**Comment by dustymabe** [comment]
For a summary of what is going on read [this section](https://github.com/dustymabe/vagrant-sshfs#sharing-vagrant-host-directory-to-vagrant-guest---94-of-users)  from the README

**Comment by dustymabe** [comment]
Closing this pending more information.
